import { db } from "../database.js";
import { getTransporter, sendEmailWithTimeout, getApiSettings } from "../config/apiResolvers.js";

/**
 * Creates an admin notification in the database and concurrently emails the administrator.
 */
export async function createAdminNotification({ type, title, message, userEmail = null }) {
  try {
    // 1. Persist notification to DB
    const notif = await db.notifications.create({
      data: {
        type,
        title,
        message,
        isRead: false,
        userEmail
      }
    });

    // 2. Concurrently mail the administrator if SMTP is active
    try {
      const activeTransporter = await getTransporter();
      if (activeTransporter) {
        const apiSettings = await getApiSettings();
        const adminEmail = process.env.ADMIN_EMAIL || apiSettings?.nodemailerUser || "admin@vrixjewels.com";
        const senderEmail = apiSettings?.nodemailerUser || process.env.SMTP_USER || "info@vrixjewels.com";

        await sendEmailWithTimeout(activeTransporter, {
          from: `"VRIX Notification System" <${senderEmail}>`,
          to: adminEmail,
          subject: `🔔 VRIX Admin Alert: ${title}`,
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 24px; background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px;">
              <div style="border-bottom: 2px solid #0f172a; padding-bottom: 16px; margin-bottom: 20px;">
                <h1 style="font-size: 20px; color: #0f172a; margin: 0; text-transform: uppercase; letter-spacing: 2px;">VRIX Administrator Alert</h1>
                <p style="color: #64748b; font-size: 12px; margin: 4px 0 0 0;">Real-Time Notification System Trigger</p>
              </div>
              
              <div style="background-color: #ffffff; padding: 20px; border: 1px solid #e2e8f0; border-radius: 6px; margin-bottom: 20px;">
                <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 12px;">
                  <span style="font-size: 24px;">🔔</span>
                  <strong style="font-size: 16px; color: #0f172a;">${title}</strong>
                </div>
                <p style="color: #334155; font-size: 14px; line-height: 1.6; margin: 0;">${message}</p>
                ${userEmail ? `<p style="font-size: 12px; color: #64748b; margin-top: 14px;"><strong>Target User:</strong> ${userEmail}</p>` : ""}
              </div>

              <div style="border-t: 1px solid #e2e8f0; padding-top: 14px; text-align: center;">
                <a href="${process.env.FRONTEND_URL || 'http://localhost:3000'}/admin" style="display: inline-block; background-color: #0f172a; color: #ffffff; text-decoration: none; padding: 10px 20px; font-size: 12px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; border-radius: 4px;">Open Admin Dashboard</a>
              </div>
              
              <p style="color: #94a3b8; font-size: 10px; text-align: center; margin-top: 24px;">This is an automated alert generated by the VRIX luxury management portal.</p>
            </div>
          `,
        }, 12000);
      }
    } catch (mailErr) {
      console.warn("Mail dispatch failed for notification:", mailErr.message);
    }

    return notif;
  } catch (err) {
    console.error("Failed to create admin notification:", err.message);
    return null;
  }
}
